# Workflow de despliegue automático
# Este workflow se ejecuta automáticamente cuando se hace push a la rama master
name: Deploy

# Configuración del trigger del workflow
on:
  push:
    branches:
      - master

jobs:
  # Job principal de despliegue
  build:
    # Ejecuta en el último Ubuntu disponible
    runs-on: ubuntu-latest

    # Servicios necesarios para el job
    # services:
    #   # Configuración de Redis como servicio
    #   redis:
    #     image: redis
    #     ports:
    #       - 6379:6379

    # steps:
    #   # Instalación de herramientas de Redis
    #   - name: Install redis cli
    #     run: sudo apt-get update -y && sudo apt-get install redis-tools -y

    #   # Verificación de la conexión a Redis
    #   - name: Test Redis Connection
    #     run: redis-cli -h localhost -p 6379 ping

      # Depuración: Impresión de variables de entorno y contexto de GitHub
      - name: Print variables
        run: |
          echo "GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}"
          echo "GITHUB_REPOSITORY: ${{ github.repository }}"
          echo "GITHUB_REF: ${{ github.ref }}"
          echo "GITHUB_SHA: ${{ github.sha }}"
          echo "GITHUB_EVENT_NAME: ${{ github.event_name }}"
          echo "GITHUB_WORKSPACE: ${{ github.workspace }}"
          echo "GITHUB_ACTION: ${{ github.action }}"
          echo "GITHUB_ACTOR: ${{ github.actor }}"
          echo "GITHUB_VARIABLE: ${{ env.NAME }}"

      # Configuración del entorno Node.js
      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Descarga del código fuente del repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # Instalación de dependencias del proyecto
      - name: Install dependencies
        run: npm install

      # Ejecución de pruebas automatizadas
      - name: Run tests
        run: npm run test

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action