name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      - name: redis
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Install redis cli
        run: sudo apt-get update -y && sudo apt-get install redis-tools -y

      - name: Test Redis Connection
        run: redis-cli -h localhost -p 6379 ping

      - name: Print variables
        run: |
          echo "GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}"
          echo "GITHUB_REPOSITORY: ${{ github.repository }}"
          echo "GITHUB_REF: ${{ github.ref }}"
          echo "GITHUB_SHA: ${{ github.sha }}"
          echo "GITHUB_EVENT_NAME: ${{ github.event_name }}"
          echo "GITHUB_WORKSPACE: ${{ github.workspace }}"
          echo "GITHUB_ACTION: ${{ github.action }}"
          echo "GITHUB_ACTOR: ${{ github.actor }}"
          echo "GITHUB_VARIABLE: ${{ env.NAME }}"

      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: 20